version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: all
    versioning-strategy: auto

  - package-ecosystem: bundler
    directory: "/gemfile_steep"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: all
    versioning-strategy: lockfile-only

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
